// Copyright 2024 Apache SeaTunnel
// Licensed under the Apache License, Version 2.0

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v5.28.3
// source: internal/proto/agent/agent.proto

package agent

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// CommandType - 指令类型枚举
type CommandType int32

const (
	CommandType_COMMAND_TYPE_UNSPECIFIED CommandType = 0
	// 预检查
	CommandType_PRECHECK CommandType = 1
	// 安装类
	CommandType_INSTALL   CommandType = 10
	CommandType_UNINSTALL CommandType = 11
	CommandType_UPGRADE   CommandType = 12
	// 进程管理
	CommandType_START   CommandType = 20
	CommandType_STOP    CommandType = 21
	CommandType_RESTART CommandType = 22
	CommandType_STATUS  CommandType = 23
	// 诊断类
	CommandType_COLLECT_LOGS CommandType = 30
	CommandType_JVM_DUMP     CommandType = 31
	CommandType_THREAD_DUMP  CommandType = 32
	// 配置类
	CommandType_UPDATE_CONFIG   CommandType = 40
	CommandType_ROLLBACK_CONFIG CommandType = 41
	CommandType_PULL_CONFIG     CommandType = 42 // 拉取配置文件
	// 插件管理
	CommandType_TRANSFER_PLUGIN  CommandType = 50 // 传输插件文件
	CommandType_INSTALL_PLUGIN   CommandType = 51 // 安装插件
	CommandType_UNINSTALL_PLUGIN CommandType = 52 // 卸载插件
	CommandType_LIST_PLUGINS     CommandType = 53 // 列出已安装插件
	// 安装包传输
	CommandType_TRANSFER_PACKAGE CommandType = 60 // 传输安装包文件
)

// Enum value maps for CommandType.
var (
	CommandType_name = map[int32]string{
		0:  "COMMAND_TYPE_UNSPECIFIED",
		1:  "PRECHECK",
		10: "INSTALL",
		11: "UNINSTALL",
		12: "UPGRADE",
		20: "START",
		21: "STOP",
		22: "RESTART",
		23: "STATUS",
		30: "COLLECT_LOGS",
		31: "JVM_DUMP",
		32: "THREAD_DUMP",
		40: "UPDATE_CONFIG",
		41: "ROLLBACK_CONFIG",
		42: "PULL_CONFIG",
		50: "TRANSFER_PLUGIN",
		51: "INSTALL_PLUGIN",
		52: "UNINSTALL_PLUGIN",
		53: "LIST_PLUGINS",
		60: "TRANSFER_PACKAGE",
	}
	CommandType_value = map[string]int32{
		"COMMAND_TYPE_UNSPECIFIED": 0,
		"PRECHECK":                 1,
		"INSTALL":                  10,
		"UNINSTALL":                11,
		"UPGRADE":                  12,
		"START":                    20,
		"STOP":                     21,
		"RESTART":                  22,
		"STATUS":                   23,
		"COLLECT_LOGS":             30,
		"JVM_DUMP":                 31,
		"THREAD_DUMP":              32,
		"UPDATE_CONFIG":            40,
		"ROLLBACK_CONFIG":          41,
		"PULL_CONFIG":              42,
		"TRANSFER_PLUGIN":          50,
		"INSTALL_PLUGIN":           51,
		"UNINSTALL_PLUGIN":         52,
		"LIST_PLUGINS":             53,
		"TRANSFER_PACKAGE":         60,
	}
)

func (x CommandType) Enum() *CommandType {
	p := new(CommandType)
	*p = x
	return p
}

func (x CommandType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (CommandType) Descriptor() protoreflect.EnumDescriptor {
	return file_internal_proto_agent_agent_proto_enumTypes[0].Descriptor()
}

func (CommandType) Type() protoreflect.EnumType {
	return &file_internal_proto_agent_agent_proto_enumTypes[0]
}

func (x CommandType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use CommandType.Descriptor instead.
func (CommandType) EnumDescriptor() ([]byte, []int) {
	return file_internal_proto_agent_agent_proto_rawDescGZIP(), []int{0}
}

// CommandStatus - 指令执行状态枚举
type CommandStatus int32

const (
	CommandStatus_COMMAND_STATUS_UNSPECIFIED CommandStatus = 0
	CommandStatus_PENDING                    CommandStatus = 1 // 等待执行
	CommandStatus_RUNNING                    CommandStatus = 2 // 执行中
	CommandStatus_SUCCESS                    CommandStatus = 3 // 执行成功
	CommandStatus_FAILED                     CommandStatus = 4 // 执行失败
	CommandStatus_CANCELLED                  CommandStatus = 5 // 已取消
)

// Enum value maps for CommandStatus.
var (
	CommandStatus_name = map[int32]string{
		0: "COMMAND_STATUS_UNSPECIFIED",
		1: "PENDING",
		2: "RUNNING",
		3: "SUCCESS",
		4: "FAILED",
		5: "CANCELLED",
	}
	CommandStatus_value = map[string]int32{
		"COMMAND_STATUS_UNSPECIFIED": 0,
		"PENDING":                    1,
		"RUNNING":                    2,
		"SUCCESS":                    3,
		"FAILED":                     4,
		"CANCELLED":                  5,
	}
)

func (x CommandStatus) Enum() *CommandStatus {
	p := new(CommandStatus)
	*p = x
	return p
}

func (x CommandStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (CommandStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_internal_proto_agent_agent_proto_enumTypes[1].Descriptor()
}

func (CommandStatus) Type() protoreflect.EnumType {
	return &file_internal_proto_agent_agent_proto_enumTypes[1]
}

func (x CommandStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use CommandStatus.Descriptor instead.
func (CommandStatus) EnumDescriptor() ([]byte, []int) {
	return file_internal_proto_agent_agent_proto_rawDescGZIP(), []int{1}
}

// LogLevel - 日志级别枚举
type LogLevel int32

const (
	LogLevel_LOG_LEVEL_UNSPECIFIED LogLevel = 0
	LogLevel_DEBUG                 LogLevel = 1
	LogLevel_INFO                  LogLevel = 2
	LogLevel_WARN                  LogLevel = 3
	LogLevel_ERROR                 LogLevel = 4
)

// Enum value maps for LogLevel.
var (
	LogLevel_name = map[int32]string{
		0: "LOG_LEVEL_UNSPECIFIED",
		1: "DEBUG",
		2: "INFO",
		3: "WARN",
		4: "ERROR",
	}
	LogLevel_value = map[string]int32{
		"LOG_LEVEL_UNSPECIFIED": 0,
		"DEBUG":                 1,
		"INFO":                  2,
		"WARN":                  3,
		"ERROR":                 4,
	}
)

func (x LogLevel) Enum() *LogLevel {
	p := new(LogLevel)
	*p = x
	return p
}

func (x LogLevel) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (LogLevel) Descriptor() protoreflect.EnumDescriptor {
	return file_internal_proto_agent_agent_proto_enumTypes[2].Descriptor()
}

func (LogLevel) Type() protoreflect.EnumType {
	return &file_internal_proto_agent_agent_proto_enumTypes[2]
}

func (x LogLevel) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use LogLevel.Descriptor instead.
func (LogLevel) EnumDescriptor() ([]byte, []int) {
	return file_internal_proto_agent_agent_proto_rawDescGZIP(), []int{2}
}

// RegisterRequest - Agent 注册请求
type RegisterRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AgentId       string                 `protobuf:"bytes,1,opt,name=agent_id,json=agentId,proto3" json:"agent_id,omitempty"`                // Agent 唯一标识
	Hostname      string                 `protobuf:"bytes,2,opt,name=hostname,proto3" json:"hostname,omitempty"`                             // 主机名
	IpAddress     string                 `protobuf:"bytes,3,opt,name=ip_address,json=ipAddress,proto3" json:"ip_address,omitempty"`          // IP 地址
	OsType        string                 `protobuf:"bytes,4,opt,name=os_type,json=osType,proto3" json:"os_type,omitempty"`                   // 操作系统类型: linux, darwin, windows
	Arch          string                 `protobuf:"bytes,5,opt,name=arch,proto3" json:"arch,omitempty"`                                     // CPU 架构: amd64, arm64
	AgentVersion  string                 `protobuf:"bytes,6,opt,name=agent_version,json=agentVersion,proto3" json:"agent_version,omitempty"` // Agent 版本号
	SystemInfo    *SystemInfo            `protobuf:"bytes,7,opt,name=system_info,json=systemInfo,proto3" json:"system_info,omitempty"`       // 系统信息
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegisterRequest) Reset() {
	*x = RegisterRequest{}
	mi := &file_internal_proto_agent_agent_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterRequest) ProtoMessage() {}

func (x *RegisterRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_proto_agent_agent_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterRequest.ProtoReflect.Descriptor instead.
func (*RegisterRequest) Descriptor() ([]byte, []int) {
	return file_internal_proto_agent_agent_proto_rawDescGZIP(), []int{0}
}

func (x *RegisterRequest) GetAgentId() string {
	if x != nil {
		return x.AgentId
	}
	return ""
}

func (x *RegisterRequest) GetHostname() string {
	if x != nil {
		return x.Hostname
	}
	return ""
}

func (x *RegisterRequest) GetIpAddress() string {
	if x != nil {
		return x.IpAddress
	}
	return ""
}

func (x *RegisterRequest) GetOsType() string {
	if x != nil {
		return x.OsType
	}
	return ""
}

func (x *RegisterRequest) GetArch() string {
	if x != nil {
		return x.Arch
	}
	return ""
}

func (x *RegisterRequest) GetAgentVersion() string {
	if x != nil {
		return x.AgentVersion
	}
	return ""
}

func (x *RegisterRequest) GetSystemInfo() *SystemInfo {
	if x != nil {
		return x.SystemInfo
	}
	return nil
}

// SystemInfo - 系统硬件信息
type SystemInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CpuCores      int32                  `protobuf:"varint,1,opt,name=cpu_cores,json=cpuCores,proto3" json:"cpu_cores,omitempty"`               // CPU 核心数
	TotalMemory   int64                  `protobuf:"varint,2,opt,name=total_memory,json=totalMemory,proto3" json:"total_memory,omitempty"`      // 总内存 (bytes)
	TotalDisk     int64                  `protobuf:"varint,3,opt,name=total_disk,json=totalDisk,proto3" json:"total_disk,omitempty"`            // 总磁盘空间 (bytes)
	KernelVersion string                 `protobuf:"bytes,4,opt,name=kernel_version,json=kernelVersion,proto3" json:"kernel_version,omitempty"` // 内核版本
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SystemInfo) Reset() {
	*x = SystemInfo{}
	mi := &file_internal_proto_agent_agent_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SystemInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SystemInfo) ProtoMessage() {}

func (x *SystemInfo) ProtoReflect() protoreflect.Message {
	mi := &file_internal_proto_agent_agent_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SystemInfo.ProtoReflect.Descriptor instead.
func (*SystemInfo) Descriptor() ([]byte, []int) {
	return file_internal_proto_agent_agent_proto_rawDescGZIP(), []int{1}
}

func (x *SystemInfo) GetCpuCores() int32 {
	if x != nil {
		return x.CpuCores
	}
	return 0
}

func (x *SystemInfo) GetTotalMemory() int64 {
	if x != nil {
		return x.TotalMemory
	}
	return 0
}

func (x *SystemInfo) GetTotalDisk() int64 {
	if x != nil {
		return x.TotalDisk
	}
	return 0
}

func (x *SystemInfo) GetKernelVersion() string {
	if x != nil {
		return x.KernelVersion
	}
	return ""
}

// RegisterResponse - Agent 注册响应
type RegisterResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`                        // 注册是否成功
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`                         // 响应消息
	AssignedId    string                 `protobuf:"bytes,3,opt,name=assigned_id,json=assignedId,proto3" json:"assigned_id,omitempty"` // Control Plane 分配的 ID
	Config        *AgentConfig           `protobuf:"bytes,4,opt,name=config,proto3" json:"config,omitempty"`                           // 下发的配置
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegisterResponse) Reset() {
	*x = RegisterResponse{}
	mi := &file_internal_proto_agent_agent_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterResponse) ProtoMessage() {}

func (x *RegisterResponse) ProtoReflect() protoreflect.Message {
	mi := &file_internal_proto_agent_agent_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterResponse.ProtoReflect.Descriptor instead.
func (*RegisterResponse) Descriptor() ([]byte, []int) {
	return file_internal_proto_agent_agent_proto_rawDescGZIP(), []int{2}
}

func (x *RegisterResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *RegisterResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *RegisterResponse) GetAssignedId() string {
	if x != nil {
		return x.AssignedId
	}
	return ""
}

func (x *RegisterResponse) GetConfig() *AgentConfig {
	if x != nil {
		return x.Config
	}
	return nil
}

// AgentConfig - Agent 配置信息
type AgentConfig struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	HeartbeatInterval int32                  `protobuf:"varint,1,opt,name=heartbeat_interval,json=heartbeatInterval,proto3" json:"heartbeat_interval,omitempty"`                         // 心跳间隔 (秒)
	LogLevel          int32                  `protobuf:"varint,2,opt,name=log_level,json=logLevel,proto3" json:"log_level,omitempty"`                                                    // 日志级别
	Extra             map[string]string      `protobuf:"bytes,3,rep,name=extra,proto3" json:"extra,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"` // 扩展配置
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *AgentConfig) Reset() {
	*x = AgentConfig{}
	mi := &file_internal_proto_agent_agent_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AgentConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AgentConfig) ProtoMessage() {}

func (x *AgentConfig) ProtoReflect() protoreflect.Message {
	mi := &file_internal_proto_agent_agent_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AgentConfig.ProtoReflect.Descriptor instead.
func (*AgentConfig) Descriptor() ([]byte, []int) {
	return file_internal_proto_agent_agent_proto_rawDescGZIP(), []int{3}
}

func (x *AgentConfig) GetHeartbeatInterval() int32 {
	if x != nil {
		return x.HeartbeatInterval
	}
	return 0
}

func (x *AgentConfig) GetLogLevel() int32 {
	if x != nil {
		return x.LogLevel
	}
	return 0
}

func (x *AgentConfig) GetExtra() map[string]string {
	if x != nil {
		return x.Extra
	}
	return nil
}

// HeartbeatRequest - 心跳请求
type HeartbeatRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AgentId       string                 `protobuf:"bytes,1,opt,name=agent_id,json=agentId,proto3" json:"agent_id,omitempty"`                   // Agent 唯一标识
	Timestamp     int64                  `protobuf:"varint,2,opt,name=timestamp,proto3" json:"timestamp,omitempty"`                             // 时间戳 (Unix 毫秒)
	ResourceUsage *ResourceUsage         `protobuf:"bytes,3,opt,name=resource_usage,json=resourceUsage,proto3" json:"resource_usage,omitempty"` // 资源使用情况
	Processes     []*ProcessStatus       `protobuf:"bytes,4,rep,name=processes,proto3" json:"processes,omitempty"`                              // 进程状态列表
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HeartbeatRequest) Reset() {
	*x = HeartbeatRequest{}
	mi := &file_internal_proto_agent_agent_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HeartbeatRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HeartbeatRequest) ProtoMessage() {}

func (x *HeartbeatRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_proto_agent_agent_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HeartbeatRequest.ProtoReflect.Descriptor instead.
func (*HeartbeatRequest) Descriptor() ([]byte, []int) {
	return file_internal_proto_agent_agent_proto_rawDescGZIP(), []int{4}
}

func (x *HeartbeatRequest) GetAgentId() string {
	if x != nil {
		return x.AgentId
	}
	return ""
}

func (x *HeartbeatRequest) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

func (x *HeartbeatRequest) GetResourceUsage() *ResourceUsage {
	if x != nil {
		return x.ResourceUsage
	}
	return nil
}

func (x *HeartbeatRequest) GetProcesses() []*ProcessStatus {
	if x != nil {
		return x.Processes
	}
	return nil
}

// ResourceUsage - 资源使用情况
type ResourceUsage struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	CpuUsage        float64                `protobuf:"fixed64,1,opt,name=cpu_usage,json=cpuUsage,proto3" json:"cpu_usage,omitempty"`                     // CPU 使用率 (0-100)
	MemoryUsage     float64                `protobuf:"fixed64,2,opt,name=memory_usage,json=memoryUsage,proto3" json:"memory_usage,omitempty"`            // 内存使用率 (0-100)
	DiskUsage       float64                `protobuf:"fixed64,3,opt,name=disk_usage,json=diskUsage,proto3" json:"disk_usage,omitempty"`                  // 磁盘使用率 (0-100)
	AvailableMemory int64                  `protobuf:"varint,4,opt,name=available_memory,json=availableMemory,proto3" json:"available_memory,omitempty"` // 可用内存 (bytes)
	AvailableDisk   int64                  `protobuf:"varint,5,opt,name=available_disk,json=availableDisk,proto3" json:"available_disk,omitempty"`       // 可用磁盘空间 (bytes)
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *ResourceUsage) Reset() {
	*x = ResourceUsage{}
	mi := &file_internal_proto_agent_agent_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ResourceUsage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResourceUsage) ProtoMessage() {}

func (x *ResourceUsage) ProtoReflect() protoreflect.Message {
	mi := &file_internal_proto_agent_agent_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResourceUsage.ProtoReflect.Descriptor instead.
func (*ResourceUsage) Descriptor() ([]byte, []int) {
	return file_internal_proto_agent_agent_proto_rawDescGZIP(), []int{5}
}

func (x *ResourceUsage) GetCpuUsage() float64 {
	if x != nil {
		return x.CpuUsage
	}
	return 0
}

func (x *ResourceUsage) GetMemoryUsage() float64 {
	if x != nil {
		return x.MemoryUsage
	}
	return 0
}

func (x *ResourceUsage) GetDiskUsage() float64 {
	if x != nil {
		return x.DiskUsage
	}
	return 0
}

func (x *ResourceUsage) GetAvailableMemory() int64 {
	if x != nil {
		return x.AvailableMemory
	}
	return 0
}

func (x *ResourceUsage) GetAvailableDisk() int64 {
	if x != nil {
		return x.AvailableDisk
	}
	return 0
}

// ProcessStatus - 进程状态信息
type ProcessStatus struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`                                   // 进程名称
	Pid           int32                  `protobuf:"varint,2,opt,name=pid,proto3" json:"pid,omitempty"`                                    // 进程 ID
	Status        string                 `protobuf:"bytes,3,opt,name=status,proto3" json:"status,omitempty"`                               // 状态: running, stopped, unknown
	Uptime        int64                  `protobuf:"varint,4,opt,name=uptime,proto3" json:"uptime,omitempty"`                              // 运行时长 (秒)
	CpuUsage      float64                `protobuf:"fixed64,5,opt,name=cpu_usage,json=cpuUsage,proto3" json:"cpu_usage,omitempty"`         // CPU 使用率
	MemoryUsage   int64                  `protobuf:"varint,6,opt,name=memory_usage,json=memoryUsage,proto3" json:"memory_usage,omitempty"` // 内存使用量 (bytes)
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ProcessStatus) Reset() {
	*x = ProcessStatus{}
	mi := &file_internal_proto_agent_agent_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProcessStatus) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProcessStatus) ProtoMessage() {}

func (x *ProcessStatus) ProtoReflect() protoreflect.Message {
	mi := &file_internal_proto_agent_agent_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProcessStatus.ProtoReflect.Descriptor instead.
func (*ProcessStatus) Descriptor() ([]byte, []int) {
	return file_internal_proto_agent_agent_proto_rawDescGZIP(), []int{6}
}

func (x *ProcessStatus) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *ProcessStatus) GetPid() int32 {
	if x != nil {
		return x.Pid
	}
	return 0
}

func (x *ProcessStatus) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *ProcessStatus) GetUptime() int64 {
	if x != nil {
		return x.Uptime
	}
	return 0
}

func (x *ProcessStatus) GetCpuUsage() float64 {
	if x != nil {
		return x.CpuUsage
	}
	return 0
}

func (x *ProcessStatus) GetMemoryUsage() int64 {
	if x != nil {
		return x.MemoryUsage
	}
	return 0
}

// HeartbeatResponse - 心跳响应
type HeartbeatResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`                         // 心跳是否成功
	ServerTime    int64                  `protobuf:"varint,2,opt,name=server_time,json=serverTime,proto3" json:"server_time,omitempty"` // 服务器时间 (Unix 毫秒)
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HeartbeatResponse) Reset() {
	*x = HeartbeatResponse{}
	mi := &file_internal_proto_agent_agent_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HeartbeatResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HeartbeatResponse) ProtoMessage() {}

func (x *HeartbeatResponse) ProtoReflect() protoreflect.Message {
	mi := &file_internal_proto_agent_agent_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HeartbeatResponse.ProtoReflect.Descriptor instead.
func (*HeartbeatResponse) Descriptor() ([]byte, []int) {
	return file_internal_proto_agent_agent_proto_rawDescGZIP(), []int{7}
}

func (x *HeartbeatResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *HeartbeatResponse) GetServerTime() int64 {
	if x != nil {
		return x.ServerTime
	}
	return 0
}

// CommandRequest - 指令请求 (Control Plane -> Agent)
type CommandRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CommandId     string                 `protobuf:"bytes,1,opt,name=command_id,json=commandId,proto3" json:"command_id,omitempty"`                                                            // 指令唯一标识
	Type          CommandType            `protobuf:"varint,2,opt,name=type,proto3,enum=seatunnel.agent.v1.CommandType" json:"type,omitempty"`                                                  // 指令类型
	Parameters    map[string]string      `protobuf:"bytes,3,rep,name=parameters,proto3" json:"parameters,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"` // 指令参数
	Timeout       int32                  `protobuf:"varint,4,opt,name=timeout,proto3" json:"timeout,omitempty"`                                                                                // 超时时间 (秒)
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CommandRequest) Reset() {
	*x = CommandRequest{}
	mi := &file_internal_proto_agent_agent_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CommandRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CommandRequest) ProtoMessage() {}

func (x *CommandRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_proto_agent_agent_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CommandRequest.ProtoReflect.Descriptor instead.
func (*CommandRequest) Descriptor() ([]byte, []int) {
	return file_internal_proto_agent_agent_proto_rawDescGZIP(), []int{8}
}

func (x *CommandRequest) GetCommandId() string {
	if x != nil {
		return x.CommandId
	}
	return ""
}

func (x *CommandRequest) GetType() CommandType {
	if x != nil {
		return x.Type
	}
	return CommandType_COMMAND_TYPE_UNSPECIFIED
}

func (x *CommandRequest) GetParameters() map[string]string {
	if x != nil {
		return x.Parameters
	}
	return nil
}

func (x *CommandRequest) GetTimeout() int32 {
	if x != nil {
		return x.Timeout
	}
	return 0
}

// CommandResponse - 指令执行结果 (Agent -> Control Plane)
type CommandResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CommandId     string                 `protobuf:"bytes,1,opt,name=command_id,json=commandId,proto3" json:"command_id,omitempty"`                 // 指令唯一标识
	Status        CommandStatus          `protobuf:"varint,2,opt,name=status,proto3,enum=seatunnel.agent.v1.CommandStatus" json:"status,omitempty"` // 执行状态
	Progress      int32                  `protobuf:"varint,3,opt,name=progress,proto3" json:"progress,omitempty"`                                   // 执行进度 (0-100)
	Output        string                 `protobuf:"bytes,4,opt,name=output,proto3" json:"output,omitempty"`                                        // 标准输出
	Error         string                 `protobuf:"bytes,5,opt,name=error,proto3" json:"error,omitempty"`                                          // 错误信息
	Timestamp     int64                  `protobuf:"varint,6,opt,name=timestamp,proto3" json:"timestamp,omitempty"`                                 // 时间戳 (Unix 毫秒)
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CommandResponse) Reset() {
	*x = CommandResponse{}
	mi := &file_internal_proto_agent_agent_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CommandResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CommandResponse) ProtoMessage() {}

func (x *CommandResponse) ProtoReflect() protoreflect.Message {
	mi := &file_internal_proto_agent_agent_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CommandResponse.ProtoReflect.Descriptor instead.
func (*CommandResponse) Descriptor() ([]byte, []int) {
	return file_internal_proto_agent_agent_proto_rawDescGZIP(), []int{9}
}

func (x *CommandResponse) GetCommandId() string {
	if x != nil {
		return x.CommandId
	}
	return ""
}

func (x *CommandResponse) GetStatus() CommandStatus {
	if x != nil {
		return x.Status
	}
	return CommandStatus_COMMAND_STATUS_UNSPECIFIED
}

func (x *CommandResponse) GetProgress() int32 {
	if x != nil {
		return x.Progress
	}
	return 0
}

func (x *CommandResponse) GetOutput() string {
	if x != nil {
		return x.Output
	}
	return ""
}

func (x *CommandResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

func (x *CommandResponse) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

// LogEntry - 日志条目
type LogEntry struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AgentId       string                 `protobuf:"bytes,1,opt,name=agent_id,json=agentId,proto3" json:"agent_id,omitempty"`                                                          // Agent 唯一标识
	CommandId     string                 `protobuf:"bytes,2,opt,name=command_id,json=commandId,proto3" json:"command_id,omitempty"`                                                    // 关联的指令 ID (可选)
	Timestamp     int64                  `protobuf:"varint,3,opt,name=timestamp,proto3" json:"timestamp,omitempty"`                                                                    // 时间戳 (Unix 毫秒)
	Level         LogLevel               `protobuf:"varint,4,opt,name=level,proto3,enum=seatunnel.agent.v1.LogLevel" json:"level,omitempty"`                                           // 日志级别
	Message       string                 `protobuf:"bytes,5,opt,name=message,proto3" json:"message,omitempty"`                                                                         // 日志消息
	Fields        map[string]string      `protobuf:"bytes,6,rep,name=fields,proto3" json:"fields,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"` // 扩展字段
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LogEntry) Reset() {
	*x = LogEntry{}
	mi := &file_internal_proto_agent_agent_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LogEntry) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LogEntry) ProtoMessage() {}

func (x *LogEntry) ProtoReflect() protoreflect.Message {
	mi := &file_internal_proto_agent_agent_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LogEntry.ProtoReflect.Descriptor instead.
func (*LogEntry) Descriptor() ([]byte, []int) {
	return file_internal_proto_agent_agent_proto_rawDescGZIP(), []int{10}
}

func (x *LogEntry) GetAgentId() string {
	if x != nil {
		return x.AgentId
	}
	return ""
}

func (x *LogEntry) GetCommandId() string {
	if x != nil {
		return x.CommandId
	}
	return ""
}

func (x *LogEntry) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

func (x *LogEntry) GetLevel() LogLevel {
	if x != nil {
		return x.Level
	}
	return LogLevel_LOG_LEVEL_UNSPECIFIED
}

func (x *LogEntry) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *LogEntry) GetFields() map[string]string {
	if x != nil {
		return x.Fields
	}
	return nil
}

// LogStreamResponse - 日志流响应
type LogStreamResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`                                  // 是否成功
	ReceivedCount int64                  `protobuf:"varint,2,opt,name=received_count,json=receivedCount,proto3" json:"received_count,omitempty"` // 已接收的日志条数
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LogStreamResponse) Reset() {
	*x = LogStreamResponse{}
	mi := &file_internal_proto_agent_agent_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LogStreamResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LogStreamResponse) ProtoMessage() {}

func (x *LogStreamResponse) ProtoReflect() protoreflect.Message {
	mi := &file_internal_proto_agent_agent_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LogStreamResponse.ProtoReflect.Descriptor instead.
func (*LogStreamResponse) Descriptor() ([]byte, []int) {
	return file_internal_proto_agent_agent_proto_rawDescGZIP(), []int{11}
}

func (x *LogStreamResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *LogStreamResponse) GetReceivedCount() int64 {
	if x != nil {
		return x.ReceivedCount
	}
	return 0
}

// TransferPluginRequest - 传输插件文件请求 (复用文件传输流)
type TransferPluginRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PluginName    string                 `protobuf:"bytes,1,opt,name=plugin_name,json=pluginName,proto3" json:"plugin_name,omitempty"` // 插件名称
	Version       string                 `protobuf:"bytes,2,opt,name=version,proto3" json:"version,omitempty"`                         // 版本号
	FileType      string                 `protobuf:"bytes,3,opt,name=file_type,json=fileType,proto3" json:"file_type,omitempty"`       // 文件类型: connector, dependency
	FileName      string                 `protobuf:"bytes,4,opt,name=file_name,json=fileName,proto3" json:"file_name,omitempty"`       // 文件名
	Chunk         []byte                 `protobuf:"bytes,5,opt,name=chunk,proto3" json:"chunk,omitempty"`                             // 文件块数据
	Offset        int64                  `protobuf:"varint,6,opt,name=offset,proto3" json:"offset,omitempty"`                          // 偏移量
	TotalSize     int64                  `protobuf:"varint,7,opt,name=total_size,json=totalSize,proto3" json:"total_size,omitempty"`   // 总大小
	IsLast        bool                   `protobuf:"varint,8,opt,name=is_last,json=isLast,proto3" json:"is_last,omitempty"`            // 是否最后一块
	Checksum      string                 `protobuf:"bytes,9,opt,name=checksum,proto3" json:"checksum,omitempty"`                       // SHA1 校验和 (仅最后一块)
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TransferPluginRequest) Reset() {
	*x = TransferPluginRequest{}
	mi := &file_internal_proto_agent_agent_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TransferPluginRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TransferPluginRequest) ProtoMessage() {}

func (x *TransferPluginRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_proto_agent_agent_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TransferPluginRequest.ProtoReflect.Descriptor instead.
func (*TransferPluginRequest) Descriptor() ([]byte, []int) {
	return file_internal_proto_agent_agent_proto_rawDescGZIP(), []int{12}
}

func (x *TransferPluginRequest) GetPluginName() string {
	if x != nil {
		return x.PluginName
	}
	return ""
}

func (x *TransferPluginRequest) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

func (x *TransferPluginRequest) GetFileType() string {
	if x != nil {
		return x.FileType
	}
	return ""
}

func (x *TransferPluginRequest) GetFileName() string {
	if x != nil {
		return x.FileName
	}
	return ""
}

func (x *TransferPluginRequest) GetChunk() []byte {
	if x != nil {
		return x.Chunk
	}
	return nil
}

func (x *TransferPluginRequest) GetOffset() int64 {
	if x != nil {
		return x.Offset
	}
	return 0
}

func (x *TransferPluginRequest) GetTotalSize() int64 {
	if x != nil {
		return x.TotalSize
	}
	return 0
}

func (x *TransferPluginRequest) GetIsLast() bool {
	if x != nil {
		return x.IsLast
	}
	return false
}

func (x *TransferPluginRequest) GetChecksum() string {
	if x != nil {
		return x.Checksum
	}
	return ""
}

// TransferPluginResponse - 传输插件文件响应
type TransferPluginResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`                                  // 是否成功
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`                                   // 消息
	ReceivedBytes int64                  `protobuf:"varint,3,opt,name=received_bytes,json=receivedBytes,proto3" json:"received_bytes,omitempty"` // 已接收字节数
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TransferPluginResponse) Reset() {
	*x = TransferPluginResponse{}
	mi := &file_internal_proto_agent_agent_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TransferPluginResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TransferPluginResponse) ProtoMessage() {}

func (x *TransferPluginResponse) ProtoReflect() protoreflect.Message {
	mi := &file_internal_proto_agent_agent_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TransferPluginResponse.ProtoReflect.Descriptor instead.
func (*TransferPluginResponse) Descriptor() ([]byte, []int) {
	return file_internal_proto_agent_agent_proto_rawDescGZIP(), []int{13}
}

func (x *TransferPluginResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *TransferPluginResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *TransferPluginResponse) GetReceivedBytes() int64 {
	if x != nil {
		return x.ReceivedBytes
	}
	return 0
}

// InstallPluginRequest - 安装插件请求
type InstallPluginRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PluginName    string                 `protobuf:"bytes,1,opt,name=plugin_name,json=pluginName,proto3" json:"plugin_name,omitempty"`    // 插件名称
	Version       string                 `protobuf:"bytes,2,opt,name=version,proto3" json:"version,omitempty"`                            // 版本号
	InstallPath   string                 `protobuf:"bytes,3,opt,name=install_path,json=installPath,proto3" json:"install_path,omitempty"` // SeaTunnel 安装路径
	Dependencies  []string               `protobuf:"bytes,4,rep,name=dependencies,proto3" json:"dependencies,omitempty"`                  // 依赖库文件名列表
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *InstallPluginRequest) Reset() {
	*x = InstallPluginRequest{}
	mi := &file_internal_proto_agent_agent_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InstallPluginRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InstallPluginRequest) ProtoMessage() {}

func (x *InstallPluginRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_proto_agent_agent_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InstallPluginRequest.ProtoReflect.Descriptor instead.
func (*InstallPluginRequest) Descriptor() ([]byte, []int) {
	return file_internal_proto_agent_agent_proto_rawDescGZIP(), []int{14}
}

func (x *InstallPluginRequest) GetPluginName() string {
	if x != nil {
		return x.PluginName
	}
	return ""
}

func (x *InstallPluginRequest) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

func (x *InstallPluginRequest) GetInstallPath() string {
	if x != nil {
		return x.InstallPath
	}
	return ""
}

func (x *InstallPluginRequest) GetDependencies() []string {
	if x != nil {
		return x.Dependencies
	}
	return nil
}

// InstallPluginResponse - 安装插件响应
type InstallPluginResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`                                 // 是否成功
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`                                  // 消息
	Error         string                 `protobuf:"bytes,3,opt,name=error,proto3" json:"error,omitempty"`                                      // 错误信息
	ConnectorPath string                 `protobuf:"bytes,4,opt,name=connector_path,json=connectorPath,proto3" json:"connector_path,omitempty"` // 连接器安装路径
	LibPaths      []string               `protobuf:"bytes,5,rep,name=lib_paths,json=libPaths,proto3" json:"lib_paths,omitempty"`                // 依赖库安装路径列表
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *InstallPluginResponse) Reset() {
	*x = InstallPluginResponse{}
	mi := &file_internal_proto_agent_agent_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InstallPluginResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InstallPluginResponse) ProtoMessage() {}

func (x *InstallPluginResponse) ProtoReflect() protoreflect.Message {
	mi := &file_internal_proto_agent_agent_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InstallPluginResponse.ProtoReflect.Descriptor instead.
func (*InstallPluginResponse) Descriptor() ([]byte, []int) {
	return file_internal_proto_agent_agent_proto_rawDescGZIP(), []int{15}
}

func (x *InstallPluginResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *InstallPluginResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *InstallPluginResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

func (x *InstallPluginResponse) GetConnectorPath() string {
	if x != nil {
		return x.ConnectorPath
	}
	return ""
}

func (x *InstallPluginResponse) GetLibPaths() []string {
	if x != nil {
		return x.LibPaths
	}
	return nil
}

// UninstallPluginRequest - 卸载插件请求
type UninstallPluginRequest struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	PluginName         string                 `protobuf:"bytes,1,opt,name=plugin_name,json=pluginName,proto3" json:"plugin_name,omitempty"`                          // 插件名称
	Version            string                 `protobuf:"bytes,2,opt,name=version,proto3" json:"version,omitempty"`                                                  // 版本号
	InstallPath        string                 `protobuf:"bytes,3,opt,name=install_path,json=installPath,proto3" json:"install_path,omitempty"`                       // SeaTunnel 安装路径
	RemoveDependencies bool                   `protobuf:"varint,4,opt,name=remove_dependencies,json=removeDependencies,proto3" json:"remove_dependencies,omitempty"` // 是否删除依赖库
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *UninstallPluginRequest) Reset() {
	*x = UninstallPluginRequest{}
	mi := &file_internal_proto_agent_agent_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UninstallPluginRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UninstallPluginRequest) ProtoMessage() {}

func (x *UninstallPluginRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_proto_agent_agent_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UninstallPluginRequest.ProtoReflect.Descriptor instead.
func (*UninstallPluginRequest) Descriptor() ([]byte, []int) {
	return file_internal_proto_agent_agent_proto_rawDescGZIP(), []int{16}
}

func (x *UninstallPluginRequest) GetPluginName() string {
	if x != nil {
		return x.PluginName
	}
	return ""
}

func (x *UninstallPluginRequest) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

func (x *UninstallPluginRequest) GetInstallPath() string {
	if x != nil {
		return x.InstallPath
	}
	return ""
}

func (x *UninstallPluginRequest) GetRemoveDependencies() bool {
	if x != nil {
		return x.RemoveDependencies
	}
	return false
}

// UninstallPluginResponse - 卸载插件响应
type UninstallPluginResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"` // 是否成功
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`  // 消息
	Error         string                 `protobuf:"bytes,3,opt,name=error,proto3" json:"error,omitempty"`      // 错误信息
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UninstallPluginResponse) Reset() {
	*x = UninstallPluginResponse{}
	mi := &file_internal_proto_agent_agent_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UninstallPluginResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UninstallPluginResponse) ProtoMessage() {}

func (x *UninstallPluginResponse) ProtoReflect() protoreflect.Message {
	mi := &file_internal_proto_agent_agent_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UninstallPluginResponse.ProtoReflect.Descriptor instead.
func (*UninstallPluginResponse) Descriptor() ([]byte, []int) {
	return file_internal_proto_agent_agent_proto_rawDescGZIP(), []int{17}
}

func (x *UninstallPluginResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *UninstallPluginResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *UninstallPluginResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

// ListInstalledPluginsRequest - 获取已安装插件列表请求
type ListInstalledPluginsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	InstallPath   string                 `protobuf:"bytes,1,opt,name=install_path,json=installPath,proto3" json:"install_path,omitempty"` // SeaTunnel 安装路径
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListInstalledPluginsRequest) Reset() {
	*x = ListInstalledPluginsRequest{}
	mi := &file_internal_proto_agent_agent_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListInstalledPluginsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListInstalledPluginsRequest) ProtoMessage() {}

func (x *ListInstalledPluginsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_proto_agent_agent_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListInstalledPluginsRequest.ProtoReflect.Descriptor instead.
func (*ListInstalledPluginsRequest) Descriptor() ([]byte, []int) {
	return file_internal_proto_agent_agent_proto_rawDescGZIP(), []int{18}
}

func (x *ListInstalledPluginsRequest) GetInstallPath() string {
	if x != nil {
		return x.InstallPath
	}
	return ""
}

// InstalledPluginInfo - 已安装插件信息
type InstalledPluginInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`                                        // 插件名称
	Version       string                 `protobuf:"bytes,2,opt,name=version,proto3" json:"version,omitempty"`                                  // 版本号
	ConnectorPath string                 `protobuf:"bytes,3,opt,name=connector_path,json=connectorPath,proto3" json:"connector_path,omitempty"` // 连接器路径
	Size          int64                  `protobuf:"varint,4,opt,name=size,proto3" json:"size,omitempty"`                                       // 文件大小
	InstalledAt   int64                  `protobuf:"varint,5,opt,name=installed_at,json=installedAt,proto3" json:"installed_at,omitempty"`      // 安装时间 (Unix 毫秒)
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *InstalledPluginInfo) Reset() {
	*x = InstalledPluginInfo{}
	mi := &file_internal_proto_agent_agent_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InstalledPluginInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InstalledPluginInfo) ProtoMessage() {}

func (x *InstalledPluginInfo) ProtoReflect() protoreflect.Message {
	mi := &file_internal_proto_agent_agent_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InstalledPluginInfo.ProtoReflect.Descriptor instead.
func (*InstalledPluginInfo) Descriptor() ([]byte, []int) {
	return file_internal_proto_agent_agent_proto_rawDescGZIP(), []int{19}
}

func (x *InstalledPluginInfo) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *InstalledPluginInfo) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

func (x *InstalledPluginInfo) GetConnectorPath() string {
	if x != nil {
		return x.ConnectorPath
	}
	return ""
}

func (x *InstalledPluginInfo) GetSize() int64 {
	if x != nil {
		return x.Size
	}
	return 0
}

func (x *InstalledPluginInfo) GetInstalledAt() int64 {
	if x != nil {
		return x.InstalledAt
	}
	return 0
}

// ListInstalledPluginsResponse - 获取已安装插件列表响应
type ListInstalledPluginsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"` // 是否成功
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`  // 消息
	Plugins       []*InstalledPluginInfo `protobuf:"bytes,3,rep,name=plugins,proto3" json:"plugins,omitempty"`  // 插件列表
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListInstalledPluginsResponse) Reset() {
	*x = ListInstalledPluginsResponse{}
	mi := &file_internal_proto_agent_agent_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListInstalledPluginsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListInstalledPluginsResponse) ProtoMessage() {}

func (x *ListInstalledPluginsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_internal_proto_agent_agent_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListInstalledPluginsResponse.ProtoReflect.Descriptor instead.
func (*ListInstalledPluginsResponse) Descriptor() ([]byte, []int) {
	return file_internal_proto_agent_agent_proto_rawDescGZIP(), []int{20}
}

func (x *ListInstalledPluginsResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *ListInstalledPluginsResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *ListInstalledPluginsResponse) GetPlugins() []*InstalledPluginInfo {
	if x != nil {
		return x.Plugins
	}
	return nil
}

// TransferPackageRequest - 传输安装包请求 (分块传输)
type TransferPackageRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Version       string                 `protobuf:"bytes,1,opt,name=version,proto3" json:"version,omitempty"`                       // SeaTunnel 版本号
	FileName      string                 `protobuf:"bytes,2,opt,name=file_name,json=fileName,proto3" json:"file_name,omitempty"`     // 文件名 (apache-seatunnel-{version}-bin.tar.gz)
	Chunk         []byte                 `protobuf:"bytes,3,opt,name=chunk,proto3" json:"chunk,omitempty"`                           // 文件块数据
	Offset        int64                  `protobuf:"varint,4,opt,name=offset,proto3" json:"offset,omitempty"`                        // 偏移量
	TotalSize     int64                  `protobuf:"varint,5,opt,name=total_size,json=totalSize,proto3" json:"total_size,omitempty"` // 总大小
	IsLast        bool                   `protobuf:"varint,6,opt,name=is_last,json=isLast,proto3" json:"is_last,omitempty"`          // 是否最后一块
	Checksum      string                 `protobuf:"bytes,7,opt,name=checksum,proto3" json:"checksum,omitempty"`                     // SHA256 校验和 (仅最后一块)
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TransferPackageRequest) Reset() {
	*x = TransferPackageRequest{}
	mi := &file_internal_proto_agent_agent_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TransferPackageRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TransferPackageRequest) ProtoMessage() {}

func (x *TransferPackageRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_proto_agent_agent_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TransferPackageRequest.ProtoReflect.Descriptor instead.
func (*TransferPackageRequest) Descriptor() ([]byte, []int) {
	return file_internal_proto_agent_agent_proto_rawDescGZIP(), []int{21}
}

func (x *TransferPackageRequest) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

func (x *TransferPackageRequest) GetFileName() string {
	if x != nil {
		return x.FileName
	}
	return ""
}

func (x *TransferPackageRequest) GetChunk() []byte {
	if x != nil {
		return x.Chunk
	}
	return nil
}

func (x *TransferPackageRequest) GetOffset() int64 {
	if x != nil {
		return x.Offset
	}
	return 0
}

func (x *TransferPackageRequest) GetTotalSize() int64 {
	if x != nil {
		return x.TotalSize
	}
	return 0
}

func (x *TransferPackageRequest) GetIsLast() bool {
	if x != nil {
		return x.IsLast
	}
	return false
}

func (x *TransferPackageRequest) GetChecksum() string {
	if x != nil {
		return x.Checksum
	}
	return ""
}

// TransferPackageResponse - 传输安装包响应
type TransferPackageResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`                                  // 是否成功
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`                                   // 消息
	ReceivedBytes int64                  `protobuf:"varint,3,opt,name=received_bytes,json=receivedBytes,proto3" json:"received_bytes,omitempty"` // 已接收字节数
	LocalPath     string                 `protobuf:"bytes,4,opt,name=local_path,json=localPath,proto3" json:"local_path,omitempty"`              // 本地保存路径 (传输完成后)
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TransferPackageResponse) Reset() {
	*x = TransferPackageResponse{}
	mi := &file_internal_proto_agent_agent_proto_msgTypes[22]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TransferPackageResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TransferPackageResponse) ProtoMessage() {}

func (x *TransferPackageResponse) ProtoReflect() protoreflect.Message {
	mi := &file_internal_proto_agent_agent_proto_msgTypes[22]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TransferPackageResponse.ProtoReflect.Descriptor instead.
func (*TransferPackageResponse) Descriptor() ([]byte, []int) {
	return file_internal_proto_agent_agent_proto_rawDescGZIP(), []int{22}
}

func (x *TransferPackageResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *TransferPackageResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *TransferPackageResponse) GetReceivedBytes() int64 {
	if x != nil {
		return x.ReceivedBytes
	}
	return 0
}

func (x *TransferPackageResponse) GetLocalPath() string {
	if x != nil {
		return x.LocalPath
	}
	return ""
}

var File_internal_proto_agent_agent_proto protoreflect.FileDescriptor

const file_internal_proto_agent_agent_proto_rawDesc = "" +
	"\n" +
	" internal/proto/agent/agent.proto\x12\x12seatunnel.agent.v1\"\xfa\x01\n" +
	"\x0fRegisterRequest\x12\x19\n" +
	"\bagent_id\x18\x01 \x01(\tR\aagentId\x12\x1a\n" +
	"\bhostname\x18\x02 \x01(\tR\bhostname\x12\x1d\n" +
	"\n" +
	"ip_address\x18\x03 \x01(\tR\tipAddress\x12\x17\n" +
	"\aos_type\x18\x04 \x01(\tR\x06osType\x12\x12\n" +
	"\x04arch\x18\x05 \x01(\tR\x04arch\x12#\n" +
	"\ragent_version\x18\x06 \x01(\tR\fagentVersion\x12?\n" +
	"\vsystem_info\x18\a \x01(\v2\x1e.seatunnel.agent.v1.SystemInfoR\n" +
	"systemInfo\"\x92\x01\n" +
	"\n" +
	"SystemInfo\x12\x1b\n" +
	"\tcpu_cores\x18\x01 \x01(\x05R\bcpuCores\x12!\n" +
	"\ftotal_memory\x18\x02 \x01(\x03R\vtotalMemory\x12\x1d\n" +
	"\n" +
	"total_disk\x18\x03 \x01(\x03R\ttotalDisk\x12%\n" +
	"\x0ekernel_version\x18\x04 \x01(\tR\rkernelVersion\"\xa0\x01\n" +
	"\x10RegisterResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12\x1f\n" +
	"\vassigned_id\x18\x03 \x01(\tR\n" +
	"assignedId\x127\n" +
	"\x06config\x18\x04 \x01(\v2\x1f.seatunnel.agent.v1.AgentConfigR\x06config\"\xd5\x01\n" +
	"\vAgentConfig\x12-\n" +
	"\x12heartbeat_interval\x18\x01 \x01(\x05R\x11heartbeatInterval\x12\x1b\n" +
	"\tlog_level\x18\x02 \x01(\x05R\blogLevel\x12@\n" +
	"\x05extra\x18\x03 \x03(\v2*.seatunnel.agent.v1.AgentConfig.ExtraEntryR\x05extra\x1a8\n" +
	"\n" +
	"ExtraEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\xd6\x01\n" +
	"\x10HeartbeatRequest\x12\x19\n" +
	"\bagent_id\x18\x01 \x01(\tR\aagentId\x12\x1c\n" +
	"\ttimestamp\x18\x02 \x01(\x03R\ttimestamp\x12H\n" +
	"\x0eresource_usage\x18\x03 \x01(\v2!.seatunnel.agent.v1.ResourceUsageR\rresourceUsage\x12?\n" +
	"\tprocesses\x18\x04 \x03(\v2!.seatunnel.agent.v1.ProcessStatusR\tprocesses\"\xc0\x01\n" +
	"\rResourceUsage\x12\x1b\n" +
	"\tcpu_usage\x18\x01 \x01(\x01R\bcpuUsage\x12!\n" +
	"\fmemory_usage\x18\x02 \x01(\x01R\vmemoryUsage\x12\x1d\n" +
	"\n" +
	"disk_usage\x18\x03 \x01(\x01R\tdiskUsage\x12)\n" +
	"\x10available_memory\x18\x04 \x01(\x03R\x0favailableMemory\x12%\n" +
	"\x0eavailable_disk\x18\x05 \x01(\x03R\ravailableDisk\"\xa5\x01\n" +
	"\rProcessStatus\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x10\n" +
	"\x03pid\x18\x02 \x01(\x05R\x03pid\x12\x16\n" +
	"\x06status\x18\x03 \x01(\tR\x06status\x12\x16\n" +
	"\x06uptime\x18\x04 \x01(\x03R\x06uptime\x12\x1b\n" +
	"\tcpu_usage\x18\x05 \x01(\x01R\bcpuUsage\x12!\n" +
	"\fmemory_usage\x18\x06 \x01(\x03R\vmemoryUsage\"N\n" +
	"\x11HeartbeatResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x1f\n" +
	"\vserver_time\x18\x02 \x01(\x03R\n" +
	"serverTime\"\x91\x02\n" +
	"\x0eCommandRequest\x12\x1d\n" +
	"\n" +
	"command_id\x18\x01 \x01(\tR\tcommandId\x123\n" +
	"\x04type\x18\x02 \x01(\x0e2\x1f.seatunnel.agent.v1.CommandTypeR\x04type\x12R\n" +
	"\n" +
	"parameters\x18\x03 \x03(\v22.seatunnel.agent.v1.CommandRequest.ParametersEntryR\n" +
	"parameters\x12\x18\n" +
	"\atimeout\x18\x04 \x01(\x05R\atimeout\x1a=\n" +
	"\x0fParametersEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\xd3\x01\n" +
	"\x0fCommandResponse\x12\x1d\n" +
	"\n" +
	"command_id\x18\x01 \x01(\tR\tcommandId\x129\n" +
	"\x06status\x18\x02 \x01(\x0e2!.seatunnel.agent.v1.CommandStatusR\x06status\x12\x1a\n" +
	"\bprogress\x18\x03 \x01(\x05R\bprogress\x12\x16\n" +
	"\x06output\x18\x04 \x01(\tR\x06output\x12\x14\n" +
	"\x05error\x18\x05 \x01(\tR\x05error\x12\x1c\n" +
	"\ttimestamp\x18\x06 \x01(\x03R\ttimestamp\"\xad\x02\n" +
	"\bLogEntry\x12\x19\n" +
	"\bagent_id\x18\x01 \x01(\tR\aagentId\x12\x1d\n" +
	"\n" +
	"command_id\x18\x02 \x01(\tR\tcommandId\x12\x1c\n" +
	"\ttimestamp\x18\x03 \x01(\x03R\ttimestamp\x122\n" +
	"\x05level\x18\x04 \x01(\x0e2\x1c.seatunnel.agent.v1.LogLevelR\x05level\x12\x18\n" +
	"\amessage\x18\x05 \x01(\tR\amessage\x12@\n" +
	"\x06fields\x18\x06 \x03(\v2(.seatunnel.agent.v1.LogEntry.FieldsEntryR\x06fields\x1a9\n" +
	"\vFieldsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"T\n" +
	"\x11LogStreamResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12%\n" +
	"\x0ereceived_count\x18\x02 \x01(\x03R\rreceivedCount\"\x8e\x02\n" +
	"\x15TransferPluginRequest\x12\x1f\n" +
	"\vplugin_name\x18\x01 \x01(\tR\n" +
	"pluginName\x12\x18\n" +
	"\aversion\x18\x02 \x01(\tR\aversion\x12\x1b\n" +
	"\tfile_type\x18\x03 \x01(\tR\bfileType\x12\x1b\n" +
	"\tfile_name\x18\x04 \x01(\tR\bfileName\x12\x14\n" +
	"\x05chunk\x18\x05 \x01(\fR\x05chunk\x12\x16\n" +
	"\x06offset\x18\x06 \x01(\x03R\x06offset\x12\x1d\n" +
	"\n" +
	"total_size\x18\a \x01(\x03R\ttotalSize\x12\x17\n" +
	"\ais_last\x18\b \x01(\bR\x06isLast\x12\x1a\n" +
	"\bchecksum\x18\t \x01(\tR\bchecksum\"s\n" +
	"\x16TransferPluginResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12%\n" +
	"\x0ereceived_bytes\x18\x03 \x01(\x03R\rreceivedBytes\"\x98\x01\n" +
	"\x14InstallPluginRequest\x12\x1f\n" +
	"\vplugin_name\x18\x01 \x01(\tR\n" +
	"pluginName\x12\x18\n" +
	"\aversion\x18\x02 \x01(\tR\aversion\x12!\n" +
	"\finstall_path\x18\x03 \x01(\tR\vinstallPath\x12\"\n" +
	"\fdependencies\x18\x04 \x03(\tR\fdependencies\"\xa5\x01\n" +
	"\x15InstallPluginResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12\x14\n" +
	"\x05error\x18\x03 \x01(\tR\x05error\x12%\n" +
	"\x0econnector_path\x18\x04 \x01(\tR\rconnectorPath\x12\x1b\n" +
	"\tlib_paths\x18\x05 \x03(\tR\blibPaths\"\xa7\x01\n" +
	"\x16UninstallPluginRequest\x12\x1f\n" +
	"\vplugin_name\x18\x01 \x01(\tR\n" +
	"pluginName\x12\x18\n" +
	"\aversion\x18\x02 \x01(\tR\aversion\x12!\n" +
	"\finstall_path\x18\x03 \x01(\tR\vinstallPath\x12/\n" +
	"\x13remove_dependencies\x18\x04 \x01(\bR\x12removeDependencies\"c\n" +
	"\x17UninstallPluginResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12\x14\n" +
	"\x05error\x18\x03 \x01(\tR\x05error\"@\n" +
	"\x1bListInstalledPluginsRequest\x12!\n" +
	"\finstall_path\x18\x01 \x01(\tR\vinstallPath\"\xa1\x01\n" +
	"\x13InstalledPluginInfo\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x18\n" +
	"\aversion\x18\x02 \x01(\tR\aversion\x12%\n" +
	"\x0econnector_path\x18\x03 \x01(\tR\rconnectorPath\x12\x12\n" +
	"\x04size\x18\x04 \x01(\x03R\x04size\x12!\n" +
	"\finstalled_at\x18\x05 \x01(\x03R\vinstalledAt\"\x95\x01\n" +
	"\x1cListInstalledPluginsResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12A\n" +
	"\aplugins\x18\x03 \x03(\v2'.seatunnel.agent.v1.InstalledPluginInfoR\aplugins\"\xd1\x01\n" +
	"\x16TransferPackageRequest\x12\x18\n" +
	"\aversion\x18\x01 \x01(\tR\aversion\x12\x1b\n" +
	"\tfile_name\x18\x02 \x01(\tR\bfileName\x12\x14\n" +
	"\x05chunk\x18\x03 \x01(\fR\x05chunk\x12\x16\n" +
	"\x06offset\x18\x04 \x01(\x03R\x06offset\x12\x1d\n" +
	"\n" +
	"total_size\x18\x05 \x01(\x03R\ttotalSize\x12\x17\n" +
	"\ais_last\x18\x06 \x01(\bR\x06isLast\x12\x1a\n" +
	"\bchecksum\x18\a \x01(\tR\bchecksum\"\x93\x01\n" +
	"\x17TransferPackageResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12%\n" +
	"\x0ereceived_bytes\x18\x03 \x01(\x03R\rreceivedBytes\x12\x1d\n" +
	"\n" +
	"local_path\x18\x04 \x01(\tR\tlocalPath*\xd0\x02\n" +
	"\vCommandType\x12\x1c\n" +
	"\x18COMMAND_TYPE_UNSPECIFIED\x10\x00\x12\f\n" +
	"\bPRECHECK\x10\x01\x12\v\n" +
	"\aINSTALL\x10\n" +
	"\x12\r\n" +
	"\tUNINSTALL\x10\v\x12\v\n" +
	"\aUPGRADE\x10\f\x12\t\n" +
	"\x05START\x10\x14\x12\b\n" +
	"\x04STOP\x10\x15\x12\v\n" +
	"\aRESTART\x10\x16\x12\n" +
	"\n" +
	"\x06STATUS\x10\x17\x12\x10\n" +
	"\fCOLLECT_LOGS\x10\x1e\x12\f\n" +
	"\bJVM_DUMP\x10\x1f\x12\x0f\n" +
	"\vTHREAD_DUMP\x10 \x12\x11\n" +
	"\rUPDATE_CONFIG\x10(\x12\x13\n" +
	"\x0fROLLBACK_CONFIG\x10)\x12\x13\n" +
	"\x0fTRANSFER_PLUGIN\x102\x12\x12\n" +
	"\x0eINSTALL_PLUGIN\x103\x12\x14\n" +
	"\x10UNINSTALL_PLUGIN\x104\x12\x10\n" +
	"\fLIST_PLUGINS\x105\x12\x14\n" +
	"\x10TRANSFER_PACKAGE\x10<*q\n" +
	"\rCommandStatus\x12\x1e\n" +
	"\x1aCOMMAND_STATUS_UNSPECIFIED\x10\x00\x12\v\n" +
	"\aPENDING\x10\x01\x12\v\n" +
	"\aRUNNING\x10\x02\x12\v\n" +
	"\aSUCCESS\x10\x03\x12\n" +
	"\n" +
	"\x06FAILED\x10\x04\x12\r\n" +
	"\tCANCELLED\x10\x05*O\n" +
	"\bLogLevel\x12\x19\n" +
	"\x15LOG_LEVEL_UNSPECIFIED\x10\x00\x12\t\n" +
	"\x05DEBUG\x10\x01\x12\b\n" +
	"\x04INFO\x10\x02\x12\b\n" +
	"\x04WARN\x10\x03\x12\t\n" +
	"\x05ERROR\x10\x042\xf1\x02\n" +
	"\fAgentService\x12U\n" +
	"\bRegister\x12#.seatunnel.agent.v1.RegisterRequest\x1a$.seatunnel.agent.v1.RegisterResponse\x12X\n" +
	"\tHeartbeat\x12$.seatunnel.agent.v1.HeartbeatRequest\x1a%.seatunnel.agent.v1.HeartbeatResponse\x12\\\n" +
	"\rCommandStream\x12#.seatunnel.agent.v1.CommandResponse\x1a\".seatunnel.agent.v1.CommandRequest(\x010\x01\x12R\n" +
	"\tLogStream\x12\x1c.seatunnel.agent.v1.LogEntry\x1a%.seatunnel.agent.v1.LogStreamResponse(\x01B6Z4github.com/seatunnel/seatunnelX/internal/proto/agentb\x06proto3"

var (
	file_internal_proto_agent_agent_proto_rawDescOnce sync.Once
	file_internal_proto_agent_agent_proto_rawDescData []byte
)

func file_internal_proto_agent_agent_proto_rawDescGZIP() []byte {
	file_internal_proto_agent_agent_proto_rawDescOnce.Do(func() {
		file_internal_proto_agent_agent_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_internal_proto_agent_agent_proto_rawDesc), len(file_internal_proto_agent_agent_proto_rawDesc)))
	})
	return file_internal_proto_agent_agent_proto_rawDescData
}

var file_internal_proto_agent_agent_proto_enumTypes = make([]protoimpl.EnumInfo, 3)
var file_internal_proto_agent_agent_proto_msgTypes = make([]protoimpl.MessageInfo, 26)
var file_internal_proto_agent_agent_proto_goTypes = []any{
	(CommandType)(0),                     // 0: seatunnel.agent.v1.CommandType
	(CommandStatus)(0),                   // 1: seatunnel.agent.v1.CommandStatus
	(LogLevel)(0),                        // 2: seatunnel.agent.v1.LogLevel
	(*RegisterRequest)(nil),              // 3: seatunnel.agent.v1.RegisterRequest
	(*SystemInfo)(nil),                   // 4: seatunnel.agent.v1.SystemInfo
	(*RegisterResponse)(nil),             // 5: seatunnel.agent.v1.RegisterResponse
	(*AgentConfig)(nil),                  // 6: seatunnel.agent.v1.AgentConfig
	(*HeartbeatRequest)(nil),             // 7: seatunnel.agent.v1.HeartbeatRequest
	(*ResourceUsage)(nil),                // 8: seatunnel.agent.v1.ResourceUsage
	(*ProcessStatus)(nil),                // 9: seatunnel.agent.v1.ProcessStatus
	(*HeartbeatResponse)(nil),            // 10: seatunnel.agent.v1.HeartbeatResponse
	(*CommandRequest)(nil),               // 11: seatunnel.agent.v1.CommandRequest
	(*CommandResponse)(nil),              // 12: seatunnel.agent.v1.CommandResponse
	(*LogEntry)(nil),                     // 13: seatunnel.agent.v1.LogEntry
	(*LogStreamResponse)(nil),            // 14: seatunnel.agent.v1.LogStreamResponse
	(*TransferPluginRequest)(nil),        // 15: seatunnel.agent.v1.TransferPluginRequest
	(*TransferPluginResponse)(nil),       // 16: seatunnel.agent.v1.TransferPluginResponse
	(*InstallPluginRequest)(nil),         // 17: seatunnel.agent.v1.InstallPluginRequest
	(*InstallPluginResponse)(nil),        // 18: seatunnel.agent.v1.InstallPluginResponse
	(*UninstallPluginRequest)(nil),       // 19: seatunnel.agent.v1.UninstallPluginRequest
	(*UninstallPluginResponse)(nil),      // 20: seatunnel.agent.v1.UninstallPluginResponse
	(*ListInstalledPluginsRequest)(nil),  // 21: seatunnel.agent.v1.ListInstalledPluginsRequest
	(*InstalledPluginInfo)(nil),          // 22: seatunnel.agent.v1.InstalledPluginInfo
	(*ListInstalledPluginsResponse)(nil), // 23: seatunnel.agent.v1.ListInstalledPluginsResponse
	(*TransferPackageRequest)(nil),       // 24: seatunnel.agent.v1.TransferPackageRequest
	(*TransferPackageResponse)(nil),      // 25: seatunnel.agent.v1.TransferPackageResponse
	nil,                                  // 26: seatunnel.agent.v1.AgentConfig.ExtraEntry
	nil,                                  // 27: seatunnel.agent.v1.CommandRequest.ParametersEntry
	nil,                                  // 28: seatunnel.agent.v1.LogEntry.FieldsEntry
}
var file_internal_proto_agent_agent_proto_depIdxs = []int32{
	4,  // 0: seatunnel.agent.v1.RegisterRequest.system_info:type_name -> seatunnel.agent.v1.SystemInfo
	6,  // 1: seatunnel.agent.v1.RegisterResponse.config:type_name -> seatunnel.agent.v1.AgentConfig
	26, // 2: seatunnel.agent.v1.AgentConfig.extra:type_name -> seatunnel.agent.v1.AgentConfig.ExtraEntry
	8,  // 3: seatunnel.agent.v1.HeartbeatRequest.resource_usage:type_name -> seatunnel.agent.v1.ResourceUsage
	9,  // 4: seatunnel.agent.v1.HeartbeatRequest.processes:type_name -> seatunnel.agent.v1.ProcessStatus
	0,  // 5: seatunnel.agent.v1.CommandRequest.type:type_name -> seatunnel.agent.v1.CommandType
	27, // 6: seatunnel.agent.v1.CommandRequest.parameters:type_name -> seatunnel.agent.v1.CommandRequest.ParametersEntry
	1,  // 7: seatunnel.agent.v1.CommandResponse.status:type_name -> seatunnel.agent.v1.CommandStatus
	2,  // 8: seatunnel.agent.v1.LogEntry.level:type_name -> seatunnel.agent.v1.LogLevel
	28, // 9: seatunnel.agent.v1.LogEntry.fields:type_name -> seatunnel.agent.v1.LogEntry.FieldsEntry
	22, // 10: seatunnel.agent.v1.ListInstalledPluginsResponse.plugins:type_name -> seatunnel.agent.v1.InstalledPluginInfo
	3,  // 11: seatunnel.agent.v1.AgentService.Register:input_type -> seatunnel.agent.v1.RegisterRequest
	7,  // 12: seatunnel.agent.v1.AgentService.Heartbeat:input_type -> seatunnel.agent.v1.HeartbeatRequest
	12, // 13: seatunnel.agent.v1.AgentService.CommandStream:input_type -> seatunnel.agent.v1.CommandResponse
	13, // 14: seatunnel.agent.v1.AgentService.LogStream:input_type -> seatunnel.agent.v1.LogEntry
	5,  // 15: seatunnel.agent.v1.AgentService.Register:output_type -> seatunnel.agent.v1.RegisterResponse
	10, // 16: seatunnel.agent.v1.AgentService.Heartbeat:output_type -> seatunnel.agent.v1.HeartbeatResponse
	11, // 17: seatunnel.agent.v1.AgentService.CommandStream:output_type -> seatunnel.agent.v1.CommandRequest
	14, // 18: seatunnel.agent.v1.AgentService.LogStream:output_type -> seatunnel.agent.v1.LogStreamResponse
	15, // [15:19] is the sub-list for method output_type
	11, // [11:15] is the sub-list for method input_type
	11, // [11:11] is the sub-list for extension type_name
	11, // [11:11] is the sub-list for extension extendee
	0,  // [0:11] is the sub-list for field type_name
}

func init() { file_internal_proto_agent_agent_proto_init() }
func file_internal_proto_agent_agent_proto_init() {
	if File_internal_proto_agent_agent_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_internal_proto_agent_agent_proto_rawDesc), len(file_internal_proto_agent_agent_proto_rawDesc)),
			NumEnums:      3,
			NumMessages:   26,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_internal_proto_agent_agent_proto_goTypes,
		DependencyIndexes: file_internal_proto_agent_agent_proto_depIdxs,
		EnumInfos:         file_internal_proto_agent_agent_proto_enumTypes,
		MessageInfos:      file_internal_proto_agent_agent_proto_msgTypes,
	}.Build()
	File_internal_proto_agent_agent_proto = out.File
	file_internal_proto_agent_agent_proto_goTypes = nil
	file_internal_proto_agent_agent_proto_depIdxs = nil
}
